In [6]:
from kedro.context import load_context
context = load_context("e:\\jiang\\projects\\kedro-poc\\kedro-poc\\")

shuttles=context.catalog.load('shuttles')
shuttles.head(10)

2019-10-14 20:57:54,701 - kedro.io.data_catalog - INFO - Loading data from `shuttles` (ExcelLocalDataSet)...

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,63561,Niue,Type V5,Quantum,ThetaBase Services,1.0,2,strict,1.0,f,f,"$1,325.0",35029
1,36260,Anguilla,Type V5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,780.0",30292
2,57015,Russian Federation,Type V5,Quantum,ThetaBase Services,1.0,2,moderate,0.0,f,f,"$1,715.0",19032
3,14035,Barbados,Type V5,Plasma,ThetaBase Services,3.0,6,strict,3.0,f,f,"$4,770.0",8238
4,10036,Sao Tome and Principe,Type V2,Plasma,ThetaBase Services,2.0,4,strict,2.0,f,f,"$2,820.0",30342
5,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
6,64643,Faroe Islands,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,247.0",35620
7,23389,Micronesia,Type V5,Quantum,ThetaBase Services,1.0,1,moderate,1.0,f,f,"$1,845.0",23820
8,39934,Rwanda,Type V5,Quantum,ThetaBase Services,1.0,3,strict,2.0,f,f,"$1,520.0",46528
9,57063,Faroe Islands,Type F5,Plasma,ThetaBase Services,4.0,8,strict,5.0,f,f,"$3,275.0",11875